### ISSUE TITLE
implicit declaration of function ‘_mm256_bsrli_epi128’ [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by thinkoco** [JustAMan/ffmpeg-standalone-build#2]
Hi,
On Debian 8 with gcc 4.9.2, there is no ‘_mm256_bsrli_epi128’ function in avx2intrin.h. When compiling aom, the define of  ‘_mm256_bsrli_epi128’ function  should be added to the  /usr/lib/gcc/x86_64-linux-gnu/xxxx/include/avx2intrin.h. [Here](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/avx2intrin.h) is an example.

**Comment by JustAMan** [comment]
Hello!

gcc 4.9.2 is quite an ancient version of compiler (thus it doesn't know anything about AVX), please update gcc to something more recent or disable AVX when building.
